second_project/second_app/urls.py
from django.urls import path, include 
from second_app import views
from django.contrib.auth import views as auth_views

# from second_project import second_app


app_name = 'second_app'


urlpatterns = [
   
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('edit-profile/', views.edit, name='edit'),
    path('edit_pass/',views.pass_change, name='edit_pass'),
    path('blog/',views.BlogList.as_view(),name='blog'),
    path('viewblog/',views.viewblog, name='view_blog'),
    path('viewdetail/<int:post_id>',views.viewdetail, name='view_detail'),
    path('addblog/',views.Addblog.as_view(),name='add_blog'),
    path('edit_blog/<int:post_id>',views.updateblog, name='edit_blog_form'),
    path('delete/<int:post_id>', views.delete_post,name='delete'),
    # path('update_blog/<int:pk>', views.UpdateBlog.as_view(),name='update_blog'),
    path('view_profile/', views.viewprofile,name='view_profile'),
    path('<slug:slug>/', views.post_detail, name='blog_detail'),
    # path('<slug:slug>/', views.BlogDetail.as_view(),name='blog_detail'),
    
   
    
    
    

]

second_project/second_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from second_app import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('second_app/', include ('second_app.urls') ),
    path('tinymce/', include('tinymce.urls')),
]



if settings.DEBUG: 
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   
    

second_project/templates/dashboard/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      DASHMIN - Bootstrap Admin Template
      {% endblock  %}
     </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'dashboard/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="{% static 'dashboard/https://fonts.googleapis.com' %}">
    <link rel="preconnect" href="{% static 'dashboard/https://fonts.gstatic.com' %}" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'dashboard/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary">AYOMIPOSHH</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{{request.user.userprofile.get_profile_img}}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0" style="text-transform:capitalize ;">{{request.user.get_full_name}}</h6>
                        <span></span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Blog</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'second_app:add_blog' %}" class="dropdown-item">Add Blog</a>
                            
                            <a href="{% url 'second_app:view_blog' %}" class="dropdown-item">View Blog</a>
                            <!-- <a href="" class="dropdown-item">Edit Blog</a> -->
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Profile</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'second_app:view_profile' %}" class="dropdown-item">View Profile</a>
                            
                            <a href="{% url 'second_app:edit' %}" class="dropdown-item">Edit Profile</a>
                            <a href="{% url 'second_app:edit_pass' %}" class="dropdown-item">Change Password</a>
                        </div>
                    </div>
                 </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    
                   <h4>Welcome</h4>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{{request.user.userprofile.get_profile_img}}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex" style="text-transform:capitalize ;">{{request.user.get_username}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="{% url 'second_app:view_profile' %}" class="dropdown-item">My Profile</a>
                            <a href="{% url 'second_app:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->

            {% block content %}
            {% endblock %}
            
          <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, Ayomiposhh 
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="mailto:ayomiposijoy@gmail.com">Ayomiposi Joy</a>
                        </br>
                        <!-- Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'dashboard/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'dashboard/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'dashboard/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'dashboard/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'dashboard/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'dashboard/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'dashboard/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{%static 'dashboard/js/main.js' %}"></script>
</body>

</html>

second_project/templates/dashboard/edit.html
{% extends 'dashboard/base.html' %}

{% block title %}
    edit
{% endblock %}
    

{% block content  %}
{% if messages  %}
{% for message in messages  %}
<div class="alert alert-success">{{ message }}</div>
{% endfor %}
{% endif %}
<form method="POST"enctype="multipart/form-data">
  {{ edit_key.as_p }}
  {{ up.as_p }}
  {% csrf_token  %}
  <button type="submit" value ="Edit" class="btn btn-outline-primary" style="width: 50%; ">Edit</button>
</form>
{% endblock %}

second_project/templates/dashboard/edit_blog_form.html
{% extends 'dashboard/base.html' %}

{% block title %}
  Editblog
{% endblock %}
    

{% block content  %}
{% if messages  %}
{% for message in messages  %}
<div class="alert alert-success">{{ message }}</div>
{% endfor %}
{% endif %}
<form method="POST"enctype="multipart/form-data">
  {{ editform_key.as_p }}
  {% csrf_token  %}
  <button type="submit" value ="Edit blog" class="btn btn-outline-primary" style="width: 50%; ">Edit Blog</button>
</form>
{% endblock %}

second_project/templates/dashboard/edit_pass.html
{% extends 'dashboard/base.html' %}

{% block title %}
  Change Password
{% endblock %}
    

{% block content  %}
{% if messages  %}
{% for message in messages  %}
<div class="alert alert-success">{{ message }}</div>
{% endfor %}
{% endif %}
<form method="POST"enctype="multipart/form-data">
  {{ pass_key.as_p }}
  {% csrf_token  %}
  <button type="submit" value ="Change Password" class="btn btn-outline-primary" style="width: 50%; ">Change Password</button>
</form>
{% endblock %}

second_project/templates/dashboard/form.html
{% extends 'dashboard/base.html' %}

{% block title %}
    Add Blog
{% endblock %}
    

{% block content  %}
 <h1>
  {% if not form.instance.pk %}
  Add Blog
  {% else %}
  Edit Blog
  {% endif %}
</h1>
{% if messages  %}
{% for message in messages  %}
<div class="alert alert-success">{{ message }}</div>
{% endfor %}
{% endif %}
<div>
<form method="POST"enctype="multipart/form-data" >
  {{ form.as_p }}
  {% csrf_token  %}
{% if not form.instance.pk %}
<button type="submit" value ="Add Blog" class="btn btn-outline-primary" style="width: 50%; ">Add Blog</button>
{% else %}
<button type="submit" value ="Edit Blog" class="btn btn-outline-primary" style="width: 50%; ">Edit Blog</button>
{% endif  %}
</form>
</div>
{% endblock  %}

second_project/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title  %}
Home
{% endblock %}



{% block content %}
           
        
{% endblock %}

second_project/templates/dashboard/view_profile.html
{% extends 'dashboard/base.html' %}

{% block title %}
    View Profile
{% endblock %}
    

{% block content  %}
<h1>PROFILE</h1>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card mb-3">
        <img src="{{request.user.userprofile.get_profile_img}}" alt="" class="img-fluid">
        
      </div>
      
    </div>
    <div class="col-md-6">
      <h5>Firstname: {{user.first_name}}</h5>
      </br>
      <h5>Lastname: {{user.last_name}}</h5>
      </br>
      <h6>Email: {{user.email}}</h6> 
      </br>
      <h6>Address: {{request.user.userprofile.address}}</h6>
      </br>
      <h6>Phone Number:{{request.user.userprofile.number}}</h6> 
      </br>
      <small>Website:{{request.user.userprofile.website}}</small>
      </br></br>

      <a href="{% url 'second_app:edit' %}"><button class="btn btn-primary w-100">Edit Profile</button></a>

    </div>
  </div>
</div>

{% endblock %}

second_project/templates/dashboard/viewblog.html
{% extends 'dashboard/base.html' %}

{% block title %}
    Viewblog
{% endblock %}
    

{% block content  %}
<h2>View Blogs</h2>
   <table class="table table-bordered">
     <tr>
      <th>S/N</th>
       <th>Post Title</th>
       <th>Post Content</th>
       <th>Post Image</th>
       <th>Date</th>
    <th colspan="3">Action</th>
</tr>
{% if view_blog %}
{% for v in view_blog %}

<tr>
  <td>{{ forloop.counter }}</td>
  <td>{{ v.title }}</td>
  <td><img src="{{ v.image.url }}" width="50" height="50" alt=""></td>
  <td>{{ v.content|truncatewords:30|safe }}</td>
  <td>{{ v.created_on  }}</td>
 
   <td>
     <button class="btn btn-outline-primary"><a href="{% url 'second_app:edit_blog_form' v.id %}">Edit</a></button>
  </td>
  <td>
      <button class="btn btn-outline-primary"><a href="{% url 'second_app:view_detail' v.id %}">View</a></button>
  </td>
  <td>
   <button class="btn btn-outline-danger"><a href="{% url 'second_app:delete' v.id %}">Delete</a></button>
  </td>
</tr>


{% endfor %}
{% endif %}

</table>


{% endblock %}

second_project/templates/dashboard/viewdetail.html
{% extends 'dashboard/base.html' %}


{% block title %}
{{ viewblog_detail }}
{% endblock %}
    

{% block content %}
    {% if view_detail %}
    {% for vd in view_detail %}
    <div id="colorlib-main">
      <section class="ftco-section ftco-degree-bg">
        <div class="container">
          <div class="row">
            <div class="col-md-10 col-sm-12 animate-box" data-animate-effect="fadeInLeft">
              <div class="blog-entry">
                <img src="{{ vd.image.url }} " class="img-responsive" alt="">
                <div class="desc">
                  <span><small style="color: black; font-size: 15px;">{{ vd.created_on }}</small></small> | <small> {{blog_detail.user}} </small> | <small> <i class="icon-bubble3"></i> 4</small></span>
                  <h3>{{ vd.title}}</h3>
                  <p>{{ vd.content|safe}}</p>
                <button class="btn btn-outline-primary"><a href="{% url 'second_app:view_blog' %}">Back To View Blog</a></button>
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </section>
      {% endfor %}
      {% endif %}

{% endblock %}