second_project/second_app/urls.py
from django.urls import path, include 
from second_app import views
from django.contrib.auth import views as auth_views

# from second_project import second_app


app_name = 'second_app'


urlpatterns = [
   
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('edit-profile/', views.edit, name='edit'),
    path('edit_pass/',views.pass_change, name='edit_pass'),
    path('blog/',views.BlogList.as_view(),name='blog'),
    path('viewblog/',views.viewblog, name='view_blog'),
    path('viewdetail/<int:post_id>',views.viewdetail, name='view_detail'),
    path('addblog/',views.Addblog.as_view(),name='add_blog'),
    path('edit_blog/<int:post_id>',views.updateblog, name='edit_blog_form'),
    path('delete/<int:post_id>', views.delete_post,name='delete'),
    # path('update_blog/<int:pk>', views.UpdateBlog.as_view(),name='update_blog'),
    path('view_profile/', views.viewprofile,name='view_profile'),
    path('<slug:slug>/', views.post_detail, name='blog_detail'),
    # path('<slug:slug>/', views.BlogDetail.as_view(),name='blog_detail'),
    
   
    
    
    

]

second_project/second_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from second_app import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('second_app/', include ('second_app.urls') ),
    path('tinymce/', include('tinymce.urls')),
]



if settings.DEBUG: 
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   
    

second_project/second_app/forms.py
from dataclasses import fields
from email import message
from pyexpat import model
# from pyexpat import model
# from socket import fromshare
# from unicodedata import name
from django import forms
from second_app.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.core import validators





class ContactForm(forms.ModelForm):
    name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Name'}))
    email = forms.EmailField(label='Email :', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
    message =forms.CharField(label='Message :', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Subject'}))
    
    class Meta():
     model=Contacts
     fields= ['name', 'email', 'message']
    


    
class BlogForm(forms.ModelForm):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Blog Title'}))
    slug = forms.SlugField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Slug Title'}))
    image= forms.ImageField(label='Add Image :', widget=forms.FileInput(attrs={'class': 'form-control', }))
    content=forms.CharField(label='Message :', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Subject'}))
    
    class Meta():
     model= Post
     fields= ['user','slug','title','image','content']  
     


# class RegForm(UserCreationForm):
#   class Meta():
#    model= User
#    fields= ('username','first_name','last_name','email')

class RegForm(UserCreationForm):
    username = forms.CharField(label='Username :', widget=forms.TextInput(
        attrs={'class': 'input-text', 'placeholder': 'Enter Username'}))
    email = forms.EmailField(label='Email :', widget=forms.EmailInput(attrs={'class': 'input-text', 'placeholder': 'Enter Email'}))
    first_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'input-text', 'placeholder': 'Enter Firstname'}))
    last_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'input-text', 'placeholder': 'Enter Lastname'}))
    password1 = forms.CharField(label='Enter Password :', widget=forms.PasswordInput(
        attrs={'class': 'input-text', 'placeholder': 'Enter Password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class': 'input-text', 'placeholder': 'Enter Password'}))
    botfield = forms.CharField(required=False, widget=forms.HiddenInput(),
                               validators=[validators.MaxLengthValidator(0)])

    def clean_email(self):
        email_field = self.cleaned_data.get('email')
        if User.objects.filter(email=email_field).exists():
            raise forms.ValidationError('Email already exist')
        return email_field

    class Meta():
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']
        
class EditForm(UserChangeForm):
    username = forms.CharField(label='Username :', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Username'}))
    email = forms.EmailField(label='Email :', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
    first_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Firstname'}))
    last_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Lastname'}))
    botfield = forms.CharField(required=False, widget=forms.HiddenInput(),
                               validators=[validators.MaxLengthValidator(0)])

    class Meta():
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', ]


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(
        attrs={'class':'form-control', 'placeholder':'Enter Password'}))
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(
        attrs={'class':'form-control', 'placeholder':'Enter Password'}))
    new_password2= forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class':'form-control', 'placeholder':'Enter Password'}))

    botfield = forms.CharField(required=False, widget=forms.HiddenInput(),
                               validators=[validators.MaxLengthValidator(0)])

    class Meta():
        model = User
        fields = ['password1', 'password2']

      

        
class UserForm(forms.ModelForm):
    number = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Number'}))
    image= forms.ImageField( required=False, label='Add Image :', widget=forms.FileInput(attrs={'class': 'form-control', }))
    address =forms.CharField( required=False, label='Address :', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Address'}))
    website =forms.URLField( required = False, label=' Enter Website:', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'HTTPS'}))
    
    
    class Meta():
     model= UserProfile
     fields= ['image','number','address','website']  

     
class CommentForm(forms.ModelForm):
    name = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Name'}))
    email = forms.EmailField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
    body=forms.CharField(label='Message :', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Subject'}))
    
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        
        
        
class EditBlogForm(forms.ModelForm):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Blog Title'}))
    slug = forms.SlugField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Slug Title'}))
    image= forms.ImageField(label='Add Image :', widget=forms.FileInput(attrs={'class': 'form-control', }))
    content=forms.CharField(label='Message :', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Subject'}))
    
    class Meta():
     model= Post
     fields= ['user','slug','title','image','content']  
     

second_project/second_app/views.py
from email import message
import profile
from django.shortcuts import render,redirect
from django.http import HttpResponse
from second_app.forms import *
from django.contrib.auth.models import User
from django.db import IntegrityError
from second_app.models import Post,User
from django.contrib import messages
from django.views.generic import CreateView,UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, get_object_or_404
# from. models import Blog


# Create your views here.

class BlogList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name= 'second_app/blog.html'
    context_object_name= 'blog_list'
    
# class BlogDetail(generic.DetailView):
#     model=Post
#     template_name= 'second_app/blog-single.html'
#     context_object_name= 'blog_detail'
  

def home(request):
  blog = Post.objects.filter(status=1).order_by('-created_on')[:3]
  edu = Education.objects.all()
  exp = Experience.objects.all()
  wrk = Work.objects.all()
  skl = Skill.objects.all()
  abt = About.objects.all()
  if request.method =='POST':
    contact_form = ContactForm(request.POST)
    if contact_form.is_valid():
      contact_form.save()   
  else:
    contact_form = ContactForm()
  return render(request,'second_app/index.html',{'blog':blog, 'cform':contact_form, 'edu': edu, 'exp' : exp, 'wrk':wrk,'skl': skl ,'abt' :abt })


def register(request):
  if request.method == 'POST':
    register_form=RegForm(request.POST, request.FILES)
    if register_form.is_valid():
      user = register_form.save()
      user.refresh_from_db()
      user.userprofile.first_name = register_form.cleaned_data.get('first_name')
      user.userprofile.last_name = register_form.cleaned_data.get('last_name')
      user.userprofile.email = register_form.cleaned_data.get('email')
      user.userprofile.phone = register_form.cleaned_data.get('phone')
      register_form.save()
      messages.success(request,'You have been registered')
    # return redirect('second_app:login')
    
  else:
       register_form=RegForm()
  return render(request,'second_app/register.html',{'reg': register_form})
  
  
def edit(request):
  if request.method == 'POST':
    edit=EditForm(request.POST, instance=request.user)
    user_pro = UserForm(request.POST,request.FILES,instance=request.user.userprofile)
    
    if edit.is_valid() and user_pro.is_valid():
      edit.save()
      user_pro.save()
      messages.success(request,'User edited successfully')
    
  else:
    edit=EditForm(instance=request.user)
    user_pro = UserForm(instance=request.user.userprofile)
  return render(request,'dashboard/edit.html',{'edit_key':edit, 'up': user_pro})
  
def pass_change(request):
  if request.method == 'POST':
    edit_pass = PasswordChangeForm(data=request.POST, user=request.user)
    if edit_pass.is_valid():
      edit_pass.save()
      update_session_auth_hash(request,edit_pass.user)
      messages.success(request,'Password Changed Successfully')
    
  else:
     edit_pass = PasswordChangeForm(user=request.user)
  return render(request,'dashboard/edit_pass.html',{'pass_key': edit_pass})


class Addblog(SuccessMessageMixin,CreateView):
  model =Post
  template_name ='dashboard/form.html'
  form_class =BlogForm
  success_url= reverse_lazy('second_app:add_blog')
  success_message = 'Post Added Successfully'
  
  
# class UpdateBlog(SuccessMessageMixin,UpdateView):
#   model =Post
#   template_name ='dashboard/form.html'
#   form_class =BlogForm
#   success_url= reverse_lazy('second_app:update_blog')
#   success_message = 'Update Successfully'
  
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('second_app:dashboard')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'second_app/login.html')
  
# class DeleteBlog(generic.DeleteView):
#   model =Post
#   template_name ='dashboard/viewblog.html'
#   success_url= reverse_lazy('second_app:view_blog')


def delete_post(request,post_id):
    post_record = get_object_or_404(Post,id=post_id)
    post_record.delete()
    return redirect('second_app:view_blog')
  
def logout_view(request):
       logout(request)
       return redirect('second_app:login')
  
  
def dashboard(request):
   return render(request,'dashboard/index.html')
 

def viewprofile(request):
  pro= UserProfile.objects.filter(user=request.user)
  return render(request, 'dashboard/view_profile.html',{'pro' : pro,})



def post_detail(request, slug):
    template_name= 'second_app/blog-single.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'blog_detail': post,'comments': comments,'new_comment': new_comment,'comment_form': comment_form})
  
  
def viewblog(request):
  view_blog=Post.objects.filter(user=request.user)
  return render(request, 'dashboard/viewblog.html',{'view_blog' : view_blog,})


def viewdetail(request,post_id):
  view_detail=Post.objects.filter(user=request.user,id=post_id)
  return render(request, 'dashboard/viewdetail.html',{'view_detail' : view_detail,})
    
    
    
def updateblog(request,post_id):
  edit_blog=get_object_or_404(Post,id=post_id)
  if request.method == 'POST':
    edit_blog_form = EditBlogForm(request.POST,request.FILES, instance=  edit_blog)
    if edit_blog_form.is_valid():
      edit_blog_form.save()
      messages.success(request,'Update Successfully')
    
  else:
     edit_blog_form = EditBlogForm(instance=edit_blog)
  return render(request,'dashboard/edit_blog_form.html',{'editform_key': edit_blog_form})

  

second_project/templates/second_app/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>
		{% block title %}
		
		{% endblock %}
	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'second_app/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'second_app/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'second_app/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'second_app/css/bootstrap.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'second_app/css/flexslider.css' %}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="{% static 'second_app/fonts/flaticon/font/flaticon.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'second_app/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'second_app/css/owl.theme.default.min.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'second_app/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'second_app/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
  
	<div id="colorlib-page">
		<div class="container-wrap">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="border js-fullheight">
			<div class="text-center">
				<div class="author-img" style="background-image: url({% static 'second_app/images/posh1.jpeg' %});"></div>
				<h1 id="colorlib-logo"><a href="{% url 'home' %}">Ayomiposhh</a></h1>
				<span class="position"><a href="#"> Web Developer</a> in Lagos</span>
			</div>
			<nav id="colorlib-main-menu" role="navigation" class="navbar">
				<div id="navbar" class="collapse">
					<ul>
						
						<li class="active"><a href="#" data-nav-section="home">Home</a></li>
						<li><a href="#" data-nav-section="about">About</a></li>
						<li><a href="#" data-nav-section="skills">Skills</a></li>
						<li><a href="#" data-nav-section="education">Education</a></li>
						<li><a href="#" data-nav-section="experience">Experience</a></li>
						<li><a href="#" data-nav-section="work">Work</a></li>
						<li><a href="#" data-nav-section="blog">Blog</a></li>
						<li><a href="#" data-nav-section="contact">Contact</a></li>
						
					</ul>
					
				</div>

			</nav>
			<hr>
			<div class="reg">
				<li><a href="{% url 'second_app:register' %}">Register</a></li>
				<li><a href="{% url 'second_app:login' %}"><i class="fa fa-user"></i> Login</a></li>

			</div>
			<br><br>
			<div class="colorlib-footer">
				<!-- <p><small>&copy; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
Copyright <script>document.write(new Date().getFullYear());</script> by <a href="https://themewagon.com" target="_blank">ThemeWagon</a></span> <span>Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash.com</a></span></small></p> -->
				<ul>
					<li><a href="#"><i class="icon-facebook2"></i></a></li>
					<li><a href="#"><i class="icon-twitter2"></i></a></li>
					<li><a href="#"><i class="icon-instagram"></i></a></li>
					<li><a href="#"><i class="icon-linkedin2"></i></a></li>
				</ul>
			</div>

		</aside>

    {% block content %}
    {% endblock %}
    
	

	<!-- jQuery -->
	<script src="{% static 'second_app/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'second_app/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'second_app/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'second_app/js/jquery.waypoints.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'second_app/js/jquery.flexslider-min.js' %}"></script>
	<!-- Owl carousel -->
	<script src="{% static 'second_app/js/owl.carousel.min.js' %}"></script>
	<!-- Counters -->
	<script src="{% static 'second_app/js/jquery.countTo.js' %}"></script>
	
	
	<!-- MAIN JS -->
	<script src="{% static 'second_app/js/main.js' %}"></script>

	</body>
</html>

second_project/templates/second_app/blog-single.html
{% extends 'second_app/base.html' %}

{% block title %}
{{ blog_detail.title  }}
{% endblock %}
    

{% block content %}
    {% if blog_detail %}
    <div id="colorlib-main">
      <section class="ftco-section ftco-degree-bg">
        <div class="container">
          <div class="row">
            <div class="col-md-10 col-sm-12 animate-box" data-animate-effect="fadeInLeft">
              <div class="blog-entry">
                <img src="{{ blog_detail.image.url }} " class="img-responsive" alt="">
                <div class="desc">
                  <span><small style="color: black; font-size: 15px;">{{ blog_detail.created_on }}</small></small> | <small> {{blog_detail.user}} </small> | <small> <i class="icon-bubble3"></i> 4</small></span>
                  <h3>{{ blog_detail.title}}</h3>
                  <p>{{ blog_detail.content|safe}}</p>
                
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </section>

<h1>COMMENT</h1>
      {% for comment in comments %}
      <div class="comments bg-primary" style="padding: 10px;">
        <p class="font-weight-bold">
          {{ comment.name }}
          <span class=" text-white">
            |      {{ comment.created_on }}
          </span>
        </p>
        {{ comment.body | linebreaks }}
      </div>
      {% endfor %}
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>

    </div>
  {% endif %}
  {% endblock %}

second_project/templates/second_app/blog.html
{% extends 'second_app/base.html' %}

{% block title %}
    Blog
{% endblock %}
    

{% block content  %}

    <div id="colorlib-main">
      <section class="colorlib-blog" data-section="blog">
        <div class="colorlib-narrow-content">
          <div class="row">
            {% if blog_list  %}
            {% for post in blog_list %}
            <div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
              <div class="blog-entry">
                <a href="{% url 'second_app:blog_detail' post.slug %}" class="blog-img"><img src="{{ post.image.url }} " class="img-responsive" alt=""></a>
                <div class="desc">
                  <span><small>{{ post.created_on }}</small></small> | <small> {{post.user}} </small> | <small> <i class="icon-bubble3"></i> 4</small></span>
                  <h3><a href="{% url 'second_app:blog_detail' post.slug %}">{{ post.title}}</a></h3>
                  <p>{{ post.content|truncatewords:30|safe}}</p>
                  <a href="{% url 'second_app:blog_detail' post.slug %}"><button class="btn btn-primary">Read More</button></a>
                
                </div>
              </div>
              
            </div>
            {% endfor  %}
            {% endif %}
          </div>
         
        </div>
      </section>
    </div>

       
{% endblock  %}

second_project/templates/second_app/contact.html
{% extends 'second_app/base.html' %}

{% block title %}
    Contact
{% endblock %}
    

{% block content  %}
  <form action="" method="POST">
   
    {% csrf_token %}
    {{cform.as_p}}
    
    <button type="submit" value ="Send Message" class="btn btn-outline-primary" style="width: 60%;">Send Message</button><br/>
  </form>
{% endblock %}

second_project/templates/second_app/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title  %}
    Login
    {% endblock %}
	</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Font-->
	<link rel="stylesheet" type="text/css" href="{% static 'second_app/css/opensans-font.css' %}">
	<link rel="stylesheet" type="text/css" href="fonts/line-awesome/css/line-awesome.min.css">
	<!-- Jquery -->
	<link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">
	<!-- Main Style Css -->
    <link rel="stylesheet" href="{% static 'second_app/css/style2.css' %}"/>
    <link rel="stylesheet" href="{% static 'second_app/css/bootstrap.css' %}">
</head>

<body class="form-v7">
	
	<div class="page-content">
		<div class="form-v7-content">
			
			<div class="form-center">
				<!-- <img src="{% static 'second_app/Images/reg (2).jpg' %}" alt="form"> -->
				 <!-- <p class="text-1">Sign In</p> -->
				
			</div>
			
			<form class="form-detail" action="#" method="post">
        {% if messages %}
        {% for m in messages%}
          <div class="alert alert-danger">{{ m }}</div>
        {% endfor %}
      {% endif %}
				<div class="form-row">
					<label for="username">USERNAME</label>
					<input type="text" name="username" id="username" class="input-text">
				</div>
			
				<div class="form-row">
					<label for="password">PASSWORD</label>
					<input type="password" name="password" id="password" class="input-text" required>
				</div>
				
	
					<button class="btn btn-light w-100" type="submit">Login</button>
					
			
       			 <p class="text-center"> Don't Have an Account? <a class="btn btn-primary" href="{% url 'second_app:register' %}">Sign Up</a></p>
              {% csrf_token %}
			  <a class="btn btn-primary"  href="{% url 'home' %}"> Click to go back to Home</a>
			</form>
     		</div> 
				
	</div>
	<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
	<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
  <script src="{% static 'second_app/js/bootstrap.min.js' %}"></script>
	
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

second_project/templates/second_app/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title  %}
	Register
	{% endblock %}
	</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Font-->
	<link rel="stylesheet" type="text/css" href="{% static 'second_app/css/opensans-font.css' %}">
	<link rel="stylesheet" type="text/css" href="fonts/line-awesome/css/line-awesome.min.css">
	<!-- Jquery -->
	<link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">
	<!-- Main Style Css -->
    <link rel="stylesheet" href="{% static 'second_app/css/style2.css' %}"/>
</head>
<body class="form-v7">
		<div class="page-content">
				<div class="form-v7-content">
			<div class="form-center">
				
				<!-- <img src="{% static 'second_app/images/reg (1).jpg' %}" height="600px" alt="form"> -->
				<!-- <p class="text-1 text-capitalize">Sign Up</p> -->
				
			</div>
			
			<form class="form-detail" action="#" method="post" >
				{% if messages %}
				{% for m in messages%}
					<div class="alert alert-danger">{{ m }}</div>
				{% endfor %}
			{% endif %}
			{% if reg.errors %}
       {% for field in reg %}
           {% for error in field.errors %} 
              <div class="alert alert-danger">
                   <strong style="color:red ;">{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
				{% csrf_token %}
				{{reg.as_p}}
				<div class="form-row-last">
					<input type="submit" name="register" class="register" value="Register">
					<p>Or<a href="{% url 'second_app:login' %}">Sign in</a></p>
				</div>
			</form>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
	<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
	
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>